### ISSUE TITLE
Fixes to the Biomolecular Simulations page

### ISSUE THREAD

**Issue by pinarpink** [elixir-europe/rdmkit#411] opened 2021-02-12 14:47 UTC
**Link to the page of interest**
https://rdmkit.elixir-europe.org/biomolecular_simulation_data.html

 
The following fixes are needed: 
- [x] The page does not 100% follow the template. Section names should be harmonized. E.g. "General scope"--> "Introduction".  and "Possibilities / solutions" --> "Solutions"
- [x] There is no tools table. The tools/resources mentioned in text in the solution section would need to be placed a table at the bottom.
- [x] Links to trainings on the topic is missing. 
- [ ] The part on "Type of Data to be Shared" seems to go into too much detail. By doing so we're entering the zone of the reporting checklists. Can we try summarising these bullets.
- [x] The part on "Repositories (to be extended by the community)" is rather generic guidance. Are any of these repositories being used widely by the Biomolecular simulation, if so please add them to the tools table for the page with correct tags. 
Another option is to link to the data sharing page and use the phrase "General purpose repository" in  referring text.
- [x] The part on "Data Licenses:" please link to [the existing Licensing page in the toolkit.](https://rdmkit.elixir-europe.org/licensing.html) If that page is missing the resource that is provided by you [here](https://help.data.world/hc/en-us/articles/115006114287-Common-license-types-for-datasets). Then please include that resource to the tools table on the[ Licensing page](https://rdmkit.elixir-europe.org/licensing.html).
- [x] Check the writing styling of sentences  (especially use of pronouns you vs I) and make sure it follows the agreed-upon style (this will be shared in the coming weeks by toolkit editors).

**Comment by KarelBerka** [comment] 2021-02-12 15:03
can you assign me to this issue?

**Comment by floradanna** [comment] 2021-02-18 14:01
The editors decided to remove the "External Links" paragraph from the RDMKit pages, since almost nobody was using it and it was interpreted in many ways, so we are trying to place the links that were in "External links" somewhere else (in the text directly or in tools list).

For the bimolecular simulation page, I wanted to ask you if you could integrate these external links, or only the most important onces, in the text directly maybe? Please, let me know if I can help you with this.

"External links - further references"
  - [Sharing Data from Molecular Simulations](https://doi.org/10.1021/acs.jcim.9b00665)
  - [Ten simple rules on how to create open access and reproducible molecular simulations of biological systems](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1006649)
  - [Surviving the deluge of biosimulation data](https://doi.org/10.1002/wcms.1449)
  - [An efficient and extensible format, library, and API for binary trajectory data from molecular simulations](https://doi.org/10.1002/jcc.23495)
  - [Standards for data handling](https://mmb.irbbarcelona.org/BigNASim/htmlib/help/pdf/d7.3_-_white_paper_on_standards_for_data_handling.pdf)

**Comment by pinarpink** [comment] 2021-03-17 15:27
@KarelBerka the editors reviewed issues today, let me know if more help is needed.

**Comment by KarelBerka** [comment] 2021-03-22 23:45
General tools are added 

Training is added (I have found no further training on TESS - nothing showed up on MD, molecular dynamics, etc.)

**Comment by KarelBerka** [comment] 2021-03-22 23:47
Type of Data to be Shared - we have discussed that I should try to find some policy on FAIRsharing - but there exists nothing relevant (sadly) - should it be ok if that part of the page would be transferred to a subpage in RDMtoolkit?  (but I do not know, how to make it actually)

**Comment by KarelBerka** [comment] 2021-03-23 00:39
Tools table added for all - wording tomorrow

**Comment by pinarpink** [comment] 2021-03-25 09:45
Thanks a lot @KarelBerka!  I will talk to editors and see what I can do about the "Type of Data to be Shared".

**Comment by KarelBerka** [comment] 2021-03-25 21:08
I tried to repair the wording in the pull request. Check it out if that enhanced or deteriorated the page.

**Comment by pinarpink** [comment] 2021-03-26 20:48
Thanks @KarelBerka for the changes. Now merged!

**Comment by bedroesb** [comment] 2021-06-21 22:17
hey @pinarpink Do you know if the last bullet point is tackled?

**Closed** 2021-08-28 07:46 UTC
